export const costInfoList = [
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 0,
        commonCost: 12,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 7,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 30,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 5,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 0,
        commonCost: 8,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 30,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 2,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 12,
        commonCost: 6,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 30,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 3,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Республика Казахстан - Алматы",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 0,
        commonCost: 12,
        minimumWeight: 2,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Республика Казахстан - Алматы",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Республика Казахстан - Алматы",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 30,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Республика Казахстан - Алматы",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 4,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Турция - Стамбул",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 0,
        commonCost: 14,
        minimumWeight: 2,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Турция - Стамбул",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Турция - Стамбул",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Российская Федерация - Москва",
        toBranch: "Турция - Стамбул",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Российская Федерация - Москва",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 0,
        commonCost: 12,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Российская Федерация - Москва",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Российская Федерация - Москва",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 30,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Российская Федерация - Москва",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 5,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 15,
        commonCost: 8,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 30,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 5,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 15,
        commonCost: 8,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: true
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 30,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 5,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Республика Казахстан - Алматы",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 15,
        commonCost: 8,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Республика Казахстан - Алматы",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Республика Казахстан - Алматы",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 30,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Республика Казахстан - Алматы",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 5,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Турция - Стамбул",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 0,
        commonCost: 6,
        minimumWeight: 2,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Турция - Стамбул",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Турция - Стамбул",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 30,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Узбекистан - Ташкент",
        toBranch: "Турция - Стамбул",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Российская Федерация - Москва",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 12,
        commonCost: 6,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Российская Федерация - Москва",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Российская Федерация - Москва",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 30,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Российская Федерация - Москва",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 3,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 15,
        commonCost: 8,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 30,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 5,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Республика Казахстан - Алматы",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 10,
        commonCost: 5,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Республика Казахстан - Алматы",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Республика Казахстан - Алматы",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 30,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Республика Казахстан - Алматы",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 3,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Турция - Стамбул",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 15,
        commonCost: 8,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Турция - Стамбул",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Турция - Стамбул",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: true
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Турция - Стамбул",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Кыргызстан - Бишкек",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 15,
        commonCost: 8,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 30,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 5,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 10,
        commonCost: 5,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 30,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 3,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Российская Федерация - Москва",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 0,
        commonCost: 12,
        minimumWeight: 2,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Российская Федерация - Москва",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "",
        pickup: 0,
        delivery: 0,
        isWorked: true
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Российская Федерация - Москва",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "0",
        pickup: 0,
        delivery: 0,
        isWorked: true
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Российская Федерация - Москва",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 3,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 0,
        commonCost: 12,
        minimumWeight: 2,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "",
        pickup: 0,
        delivery: 0,
        isWorked: true
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "",
        pickup: 0,
        delivery: 0,
        isWorked: true
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 6,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Турция - Стамбул",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 0,
        commonCost: 12,
        minimumWeight: 2,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Турция - Стамбул",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "",
        pickup: 0,
        delivery: 0,
        isWorked: true
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Турция - Стамбул",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "",
        pickup: 0,
        delivery: 0,
        isWorked: true
    },
    {
        fromBranch: "Республика Казахстан - Алматы",
        toBranch: "Турция - Стамбул",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Таджикистан - Душанбе",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 15,
        commonCost: 8,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Таджикистан - Душанбе",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Таджикистан - Душанбе",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 30,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Таджикистан - Душанбе",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Таджикистан - Душанбе",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Таджикистан - Душанбе",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: true
    },
    {
        fromBranch: "Республика Таджикистан - Душанбе",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Таджикистан - Душанбе",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Таджикистан - Душанбе",
        toBranch: "Российская Федерация - Москва",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 0,
        commonCost: 10,
        minimumWeight: 2,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Таджикистан - Душанбе",
        toBranch: "Российская Федерация - Москва",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Республика Таджикистан - Душанбе",
        toBranch: "Российская Федерация - Москва",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 30,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Таджикистан - Душанбе",
        toBranch: "Российская Федерация - Москва",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 3,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Таджикистан - Душанбе",
        toBranch: "Турция - Стамбул",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 15,
        commonCost: 8,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Республика Таджикистан - Душанбе",
        toBranch: "Турция - Стамбул",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "",
        pickup: 0,
        delivery: 0,
        isWorked: true
    },
    {
        fromBranch: "Республика Таджикистан - Душанбе",
        toBranch: "Турция - Стамбул",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "",
        pickup: 0,
        delivery: 0,
        isWorked: true
    },
    {
        fromBranch: "Республика Таджикистан - Душанбе",
        toBranch: "Турция - Стамбул",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Российская Федерация - Москва",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 0,
        commonCost: 12,
        minimumWeight: 2,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Российская Федерация - Москва",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 9,
        minimumWeight: 2,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Российская Федерация - Москва",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Российская Федерация - Москва",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 5,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Российская Федерация - Москва",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 0,
        commonCost: 12,
        minimumWeight: 2,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Российская Федерация - Москва",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 9,
        minimumWeight: 5,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Российская Федерация - Москва",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Российская Федерация - Москва",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 5,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 0,
        commonCost: 10,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 5.5,
        minimumWeight: 2,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 30,
        minimumWeight: 1,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Республика Узбекистан - Ташкент",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 5,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 0,
        commonCost: 6,
        minimumWeight: 2,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Республика Кыргызстан - Бишкек",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 4,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: false
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Республика Казахстан - Алматы",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 0,
        commonCost: 7,
        minimumWeight: 2,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Республика Казахстан - Алматы",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Республика Казахстан - Алматы",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Республика Казахстан - Алматы",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 4,
        minimumWeight: 10,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Экпресс (Минимальный вес 1 кг. Стоимость перевозки от 5$.)",
        firstCost: 0,
        commonCost: 5,
        minimumWeight: 2,
        message: "",
        pickup: 3,
        delivery: 3,
        isWorked: true
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Стандарт (Минимальный вес 2 кг. Стоимость перевозки 7$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Ультра (Минимальный вес 1 кг. Стоимость перевозки 30$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    },
    {
        fromBranch: "Турция - Стамбул",
        toBranch: "Республика Таджикистан - Душанбе",
        planName: "Наземная доставка (Минимальный вес 10 кг. Стоимость перевозки 3$.)",
        firstCost: 0,
        commonCost: 0,
        minimumWeight: 0,
        message: "Данное направление не существует, выберите пожалуйста другое направление",
        pickup: 0,
        delivery: 0,
        isWorked: false
    }
]