# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

on:
  push:
    branches: [ "ethnologistics.com" ]
  pull_request:
    branches: [ "ethnologistics.com" ]

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
           username: root
           server: 31.220.72.151
           port: 22
           sftp_only: true
           password: Qwertyruru2022
           local_path: './*'
           remote_path: './ethnologistics.com'
